FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production

COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY --chown=node:node tsconfig.json ./
COPY --chown=node:node src ./src

USER node
CMD ["npm", "run", "worker"]
